In [1]:
!pip3 install numpy

In [4]:
import numpy as np

In [5]:
lst=[1,2,3,4,5]
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3, 4, 5]


In [4]:
x=np.array(lst)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
x=np.array([1,2,3,4,5])
print(type(x))

tup=(3,4,5,6)
x=np.array(tup)
print(type(x))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
x=np.array([[1,2,3,4],[4,5,6,7],[5,6,7,8]])
print(x)
print(x[1][1])
print(type(x))

[[1 2 3 4]
 [4 5 6 7]
 [5 6 7 8]]
5
<class 'numpy.ndarray'>


In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,10,3)

array([1, 4, 7])

In [13]:
np.linspace(0,10,num=2)

array([ 0., 10.])

In [14]:
arr=np.array([2,4,1,3,6,5])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [18]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([7,8,9,10])
np.concatenate((x,y))

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [21]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(x)
print("-------")
print(y)
print("--------")
print(y.T) #transpose
print("--------")
print(np.concatenate((x,y),axis=0))
print("--------")
print(np.concatenate((x,y.T),axis=1))

[[1 2]
 [3 4]]
-------
[[5 6]]
--------
[[5]
 [6]]
--------
[[1 2]
 [3 4]
 [5 6]]
--------
[[1 2 5]
 [3 4 6]]


In [26]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]


In [24]:
x.ndim

3

In [27]:
x.size

15

In [28]:
x.shape

(1, 5, 3)

In [3]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
a=np.arange(6)
b=a.reshape((3,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [6]:
arr=np.array([1,2,3,4,5,6])
arr.resize((2,3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr=np.array([1,2,3,4,5,6])
arr.resize((3,4))
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [8]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [9]:
a2=a[np.newaxis, :]
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [10]:
a3=a2[np.newaxis, :]
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2 3 4 5 6]]]
(1, 1, 6)
3


In [11]:
col_vector=a[:,np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
b=np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)

(6, 1)
2


In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
print(a[a<5])

[1 2 3 4]


In [16]:
five_up=(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [17]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [18]:
a1=np.array([[1,1],
            [2,2]])
a2=np.array([[3,3],
            [4,4]])
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [19]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [21]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [22]:
print(np.hsplit(x,4))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]


In [23]:
np.hsplit(x,(3,5))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [24]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

2
[[3 4]
 [5 6]]
[1 3]


In [27]:
data=np.array([[1,2],[3,4],[5,6]])
data
print(data.max(axis=0))
print(data.max(axis=1))


[5 6]
[2 4 6]


In [29]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_value=np.unique(a)
print(unique_value)

[11 12 13 14 15 16 17 18 19 20]


In [30]:
unique_value,indices_list=np.unique(a,return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [31]:
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
unique_value=np.unique(a_2d)
print(unique_value)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
unique_rows=np.unique(a_2d,axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
unique_column=np.unique(a_2d,axis=1)
print(unique_column)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [39]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
arr.transpose()


array([[0, 3],
       [1, 4],
       [2, 5]])

In [41]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### reverse

In [43]:
arr=np.array([1,2,3,4,5,6,7,8])
reversed_arr=np.flip(arr)
print("reversed array: ",reversed_arr)

reversed array:  [8 7 6 5 4 3 2 1]


In [44]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
reversed_arr=np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [47]:
reversed_arr_row=np.flip(arr_2d,axis=0)
print(reversed_arr_row)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [49]:
reversed_arr_col=np.flip(arr_2d,axis=1)
print(reversed_arr_col)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
