In [1]:
import numpy as np

In [15]:
a=np.array([[[0,1,2],
             [3,4,5],
             [6,7,8]]])
print(a)
print("-------------------------------------")
b=np.arange(0,8)
b.resize((3,3))
print(b)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
-------------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 0]]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=arr[1,:]
print(d)


[4 5 6]


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
mul=arr1@arr2
print(mul)

32


In [42]:
b=np.arange(0,25)
b.resize((5,5))
print(b)
print("-------------------------------------")

b=np.mean(b)
print("Mean: ",b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
-------------------------------------
Mean:  12.0
