In [1]:
import numpy as np

### 1

In [20]:
a=np.array([12,15,17,19,20])
a=np.mean(a)
print(a)


16.6


In [21]:
b=np.array([12,15,17,19,20])
b=np.median(b)
print(b)

17.0


In [22]:
c=np.array([12,15,17,19,20])
c=np.std(c)
print(c)

2.870540018881465


### 2

In [29]:
mat = np.array([[1, 2], [3, 4]])

x = np.linalg.det(mat)
print(x)


-2.0000000000000004


### 3

In [34]:
b = np.random.randint(0, 101, size=10)
print(b)


[50 33 59 10 39 76 83 55 71 80]


### 4

In [41]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
d = a @ b
print(d)


[[19 22]
 [43 50]]


### 5

In [43]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True
primes = np.array([x for x in range(1, 51) if is_prime(x)])

print(primes)


[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


### 6

In [44]:
a= np.array([10, 20, 30, 40, 50])
b = (a - np.mean(a)) / np.std(a)
print(b)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 7

In [3]:
a=np.array([2, 5, 8, 11, 14, 17, 20, 23])
odd_numbers = a[a % 2 != 0]
print("Odd Numbers:", odd_numbers)


Odd Numbers: [ 5 11 17 23]


### 8

In [4]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
root=np.sqrt(a)
print(root)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


### 9

In [17]:
a= np.arange(9).reshape(3, 3)
diagonal_elements = np.diag(matrix)
print(a)
print("\n",diagonal_elements)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [0 4 8]


### 10

In [18]:
a=[2,3,4,5]
b=[10,20,30,40]
c=np.dot(a,b)
print(c)

400
