In [1]:
import numpy as np

### 1

In [11]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2

In [9]:
b=np.arange(5,14)
print(b)
x=b.reshape(3,3)
print(x)

[ 5  6  7  8  9 10 11 12 13]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


### 3

In [3]:
a = np.array([1, 2])
b = np.array([3, 4])
mul = a @ b

print(a)
print(b)
print(mul)


[1 2]
[3 4]
11


### 4

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

row = a[0, :]
column = b[:, 0]

dot_product = np.dot(row,column)

print(a)
print(b)
print("row of a : ",row)
print("colomn of b : ",column)

print("Dot product of the first row of a and the first column of b:",dot_product)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
row of a :  [1 2]
colomn of b :  [5 7]
Dot product of the first row of a and the first column of b: 19
19


### 5

In [14]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.sum(a)
print(b)

55


### 6

In [32]:
b=np.array([1,2,3,4])
b=np.product(b)
print(b)

24


### 7

In [29]:
c=np.array([1,2,3,4,5])
c=np.insert(c,2,0)
print(c)

[1 2 0 3 4 5]


### 8

In [31]:
d=np.array([1,2,3,4,5])
d=np.delete(d,3)
print(d)

[1 2 3 5]


### 9

In [39]:
e=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
five_up=9e>5]
print(five_up)


[ 6  7  8  9 10 11 12]


### 10

In [12]:
f=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]])
index=np.array([[0,0],
        [1,2],
        [2,4]])
x=f[index[:,0],index[:,1]]
print(x)

[ 1  8 15]


### 11

In [3]:
a = 0.5 * np.eye(5)
print(a)


[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


### 12

In [6]:
b = np.random.randint(0, 11, size=(3, 3, 3))
print(b)


[[[ 2  1  1]
  [ 6  2  0]
  [ 0  4  0]]

 [[ 0  8  7]
  [ 3  9  8]
  [ 1  9 10]]

 [[ 5  3  8]
  [ 6  3  7]
  [ 5  5  2]]]


### 13

In [10]:
b = np.random.randint(0, 11, size=(3, 3, 3))
row_means = np.mean(b, axis=2)
print(row_means)


[[5.33333333 4.33333333 7.33333333]
 [2.66666667 3.66666667 4.66666667]
 [5.33333333 5.66666667 3.        ]]


### 14

In [18]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

column_sd = np.std(a, axis=0)
print(column_sd)


[3.26598632 3.26598632 3.26598632 3.26598632]


### 15

In [26]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
b=np.dot(a,a.T)
print(b)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


### 16

In [28]:
c = np.eye(6)
c = np.roll(c, 1, axis=1)

print(c)


[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


### 17

In [38]:
d = np.eye(4)
x= d / d.sum(axis=1,)

print(x)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 18

In [40]:
e=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
e=np.flipud(e)
print(e)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### 19

In [45]:
f=np.array([[1,2,0,3],
           [5,4,6,7],
           [8,9,10,4],
           [2,6,4,8]])
x=np.sort(f,axis=1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  8  9 10]
 [ 2  4  6  8]]


### 20

In [48]:
g = np.eye(5)
x= np.linalg.inv(g)
print(g)
print(x)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]
